export const USER_LOGIN = "USER_LOGIN";

export const ACCESSTOKEN = "ACCESS_TOKEN";

export const CHANGE_THEME = "CHANGE_THEME";

export const DETAIL_COURSE_USER = "DETAIL_COURSE_USER";

// Warning courses

export const SHOW_WARNING = "SHOW_WARNING";

export const ADD_COURSE_SUCCESS_TYPE = "ADD_COURSE_SUCCESS_TYPE";
export const HIDDEN_WARNING = "HIDDEN_WARNING";

export const NOTIFY_SUCCESS_TYPE = "NOTIFY_SUCCESS_TYPE";
export const NOTIFY_ERROR_TYPE = "NOTIFY_ERROR_TYPE";
export const NOTIFY_WARNING_TYPE = "NOTIFY_WARNING_TYPE";
export const SHOW_NOTIF_TYPE = "SHOW_NOTIF_TYPE";
export const HIDDEN_NOTIFY_TYPE = "HIDDEN_NOTIFY_TYPE";
